#!/bin/sh
## One of these things is not like the other
#    2023-09-17

echo 'python'
python -c 'n=[1,2,3];print(str(n[0:0]))'
python -c 'n=[1,2,3];print(str(n[0:1]))'
python -c 'n=[1,2,3];print(str(n[1:0]))'

echo 'perl'
perl -E 'my @a=1..3; say @a[0..0]'
perl -E 'my @a=1..3; say @a[0..1]'
perl -E 'my @a=1..3; say @a[1..0]' # undef

echo 'raku'
raku -e  'my @a=1..3; say @a[0..0]'
raku -e  'my @a=1..3; say @a[0..1]'
raku -e  'my @a=1..3; say @a[1..0]'
