#!/usr/local/bin/perl
## download a RC page, extract Python entry
#c# 2023-09-12 based on rc-get5 (Perl)

use utf8;

use v5.36;

my $w = join '_', @ARGV;
$w =~ s#^.*wiki/##;
$w =~ s/#.*//;
$w =~ s/\*$//;
$w =~ s#^\.\./##;
$w =~ s#\s#_#g;

(my $f = $w) =~ s#/#_#g;
$f =~ s#'#_#g;
$f =~ s#\$#_#g;

if (-e "$f") {
for my $i (reverse 1..8) {
    my $j = $i + 1;
    system "mv $f.$i $f.$j" if -e "$f.$i";
}
system "mv $f $f.1" 
}

$w =~ s/'/\\'/g;

my $python = `curl -s -o - 'https://www.rosettacode.org/wiki/$w' | tee _download.html | perl -0 -npe 's/^.*id="Python".(.*?)<h2>.*/\$1/s; s/&#160;/ /sg;s#<br */>#<br/>\\n#sg' | strip-html - `;
die "No text!" if $python =~ /currently no text/i;

$python =~ s/^Python\s*\[edit\]//;
$python =~ s/\xA0//g;
$python =~ s/PythonÂ/Python /g;
$python =~ s/\n\s+\n/\n\n/g;

my $ymd = `date +%Y-%m-%d`; chomp $ymd;
my $ym  = `date +%Y.%m`; chomp $ym;

open F, ">$f";
print F <<EOP;
#!/usr/bin/env python
#u# https://rosettacode.org/wiki/$w
#c# $ymd 

$python

EOP

system "chmod +x $f";
