#!/usr/local/bin/perl
## xxx
#  David H.  2022-08-11

use Statistics::R;
 
# Create a communication bridge with R and start R
my $R = Statistics::R->new();
 
# Run simple R commands
#my $output_file = "file.ps";
#$R->run(qq`postscript("$output_file", horizontal=FALSE, width=500, height=500)`);
#$R->run(q`plot(c(1, 5, 10), type = "l")`);
#$R->run(q`dev.off()`);
 
# Pass and retrieve data (scalars or arrays)
my $input_value = 2;
$R->set('x', $input_value);
$R->run(q`y <- x^2`);
my $output_value = $R->get('y');
print "y = $output_value\n";
 
$R->stop();
